### PR TITLE
ST-202 - add playbook and roles for generic minikube

### PR DESCRIPTION
**Pull request by piersharding**
* roles
* playbook
* modified Vagrantfile
* Makefile
to support generic Minikube deployment

This moves the Ansible/Vagrant work from k8s-integration to ansible-playbooks (see: https://github.com/ska-telescope/k8s-integration/pull/6)

### CODE REVIEW

**Comment by flyingfrog81** [comment]
Ansible erroring out on ZeroMQ download because of ssl certificates issues. Can we move the package onto nexus? 

[ansible.log](https://github.com/ska-telescope/ansible-playbooks/files/3324725/ansible.log)

**Comment by piersharding** [comment]
> Ansible erroring out on ZeroMQ download because of ssl certificates issues. Can we move the package onto nexus?
> Internet Archive internetarchive Twitter
> 
> [ansible.log](https://github.com/ska-telescope/ansible-playbooks/files/3324725/ansible.log)

@Matteo04052017  Is there a dependency on zeromq being 4.0.5? If we can use a more recent version then we can get it from GitHub releases?

**Comment by flyingfrog81** [comment]
Unfortunately those dependencies are fixed as part of our TANGO build. 
I'd like to see these whole playbooks working before merging it. Can anyone test it all?

**Comment by piersharding** [comment]
Retested scenarios:
* vagrant+deploy_tangoenv.yml
* bare metal minikube+driver=none+-calico+(nginx|traefik)

**Comment by flyingfrog81** [comment]
thanks

**Pull request merged**
